# Dependencies
markdown:        kramdown
highlighter:      pygments

# Permalinks
#permalink:        pretty
#relative_permalinks: true

# Setup
name: Joshua Kuschner's Blog
title:            Joshua Kuschner
tagline:          'My personal notes, projects, and thoughts'
description:      'This site contains a summary of my professional endeavors as well as some of my personal interests and details regarding those.'
url:              https://jkuschner.dev
baseurl:          /

author:
  name:           'Joshua Kuschner'

#paginate:         5

# Custom vars
version:          2.1.0

github:
  #repo:           https://github.com/poole/hyde
